version: '3.8'

services:

  database:
    image: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  webserver:
    build: ./src
    ports:
      - 3000:3000